#cada intenção representa uma ação que o chatbot pode realizar.
class Intencao:
    TOTAL_ITENS_ESTOQUE = "TOTAL_ITENS_ESTOQUE"
    TOTAL_PRODUTOS_DISTINTOS = "TOTAL_PRODUTOS_DISTINTOS"
    PESO_TOTAL_FATURADO = "PESO_TOTAL_FATURADO"
    TOP_PRODUTOS_ESTOQUE = "TOP_PRODUTOS_ESTOQUE"
    TOP_CIDADES_FATURAMENTO = "TOP_CIDADES_FATURAMENTO"
    DESCONHECIDO = "DESCONHECIDO"
